name: append-06-43
on:
  workflow_dispatch:
  schedule:
    - cron: '43 06 * * *'

jobs:
  append:
    environment: append

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Append timestamp to Google Spread Sheeet
        uses: ./.github/actions/append
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workload-identity-provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service-account: ${{ secrets.SERVICE_ACCOUNT }}
          run-id: ${{ github.run_id }}
          hour: 06
          min: 43
          spread-sheet-id: ${{ secrets.SPREADSHEET_ID }}
          sheet-name: ${{ secrets.SHEET_NAME }}
